name: Web Playground Blog
description: Play with modern JS, front-end tooling & frameworks, backend API's and Microsoft Azure Cloud
date: 2017
permalink: /:year/:month/:day/:title

markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

logo: false
paginate: 5
baseurl: ''
domain_name: 'webplayground.io'
google_analytics: 'UA-89620501-1'
gems: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]

# Details for the RSS feed generator
url:            'http://www.webplayground.io'
author:         'Mateusz Korżel'
